# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-18 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('0', 'Criada'), ('1', 'Delegada'), ('2', 'Finalizada')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
