# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-18 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordemservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='preco',
            name='delegada',
            field=models.BooleanField(default=False),
        ),
    ]
